---
- name: Install Redis
  apt:
    name: redis-server
    state: present
    update_cache: yes
  become: true
  when: ansible_os_family == "Debian"

- name: Deploy redis.conf with custom port and bind
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0644'
  notify: Restart Redis

- name: Ensure Redis is started and enabled
  service:
    name: redis-server
    state: started
    enabled: true
  become: true
